---
- name: Show Satellite variables
  hosts: "{{ targeted_hosts }}"
  gather_facts: false
  ignore_unreachable: yes

  tasks:
  - name: Show subscription_status
    debug:
      msg: >
        Subscription Status: {{ foreman.subscription_status_label }}

  - name: Show Errata Counts
    debug:
      msg: >
        Bug fixes: {{ foreman.content_attributes.errata_counts.bugfix }},
        Security: {{ foreman.content_attributes.errata_counts.security }},
        Enhancement: {{ foreman.content_attributes.errata_counts.enhancement }},
        Total: {{ foreman.content_attributes.errata_counts.total }}
